synthetic_lending_profitability:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: target/synthetic_lending_profitability.duckdb
      schema: analytics
      threads: 4
    ci:
      type: duckdb
      path: target/ci.duckdb
      schema: analytics
      threads: 4
    snowflake_dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4

